{
  "openapi": "3.0.0",
  "info": {
    "title": "Medical Appointments API - Documentation",
    "description": "API for managing medical appointments",
    "version": "1.0.0",
    "contact": {
      "name": "Marcos Kenji Kuribayashi",
      "url": "https://marcos-website.vercel.app",
      "email": "marcosken13@gmail.com"
    }
  },

  "servers": [
    {
      "url": "http://localhost:3000/api",
      "description": "Development server"
    }
  ],

  "paths": {
    "/login": {
      "post": {
        "description": "Login to get token",
        "tags": ["Session"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "content": {
              "application/json": {
                "examples": {
                  "requiredFieldError": {
                    "value": {
                      "message": {
                        "email": ["Required"],
                        "password": ["Required"]
                      }
                    }
                  },
                  "invalidEmailError": {
                    "value": {
                      "message": {
                        "email": ["Invalid email"]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "content": {
              "application/json": {
                "examples": {
                  "invalidUserError": {
                    "value": {
                      "message": "Invalid user"
                    }
                  },
                  "wrongPasswordError": {
                    "value": {
                      "message": "Wrong password"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "description": "Create a new user",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createUser"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "CREATED",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/readUser"
                }
              }
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "content": {
              "application/json": {
                "examples": {
                  "requiredFieldError": {
                    "value": {
                      "message": {
                        "name": ["Required"],
                        "email": ["Required"],
                        "password": ["Required"]
                      }
                    }
                  },
                  "invalidEmailError": {
                    "value": {
                      "message": {
                        "email": ["Invalid email"]
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "CONFLICT",
            "content": {
              "application/json": {
                "examples": {
                  "conflictError": {
                    "value": {
                      "message": "User with this email already exists"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "login": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "createUser": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "isAdmin": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "readUser": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "isAdmin": {
            "type": "boolean",
            "default": false
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "deletedAt": {
            "type": "string",
            "nullable": true
          }
        }
      }
    }
  }
}
